language: ruby
cache: bundler
rvm:
  - 2.5.3

before_install:
  - gem update --system
  - gem install jekyll bundler jekyll-kentico

script: "JEKYLL_ENV=production bundle exec jekyll kentico --destination"
deploy:
  provider: pages
  local-dir: ./_site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master