future: true
name: Radek
auto: false
project_id: ENV_PROJECT_ID
api_key: ENV_API_KEY
posts_dir: _posts
sass:
  style: compact # possible values: nested expanded compact compressed
collections:
  authors:
    output: true
