future: true
name: Radek
auto: false
baseurl: /jekyll-blog
sass:
  style: compact # possible values: nested expanded compact compressed
exclude:
  - regen
  - content-initializer
  - README.md
plugins:
  - jekyll-kentico
  - jekyll-redirect-from
permalink: /:collection/:name
kentico:
  project_id: 53c7c06c-d108-00df-f62c-5338f11c4482
  secure_key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIwYzE2NjE5OWI2YWQ0YzFiYTQ5YWRkMGRjOTk4MDk5ZCIsImlhdCI6IjE1NTUwNjYyMjgiLCJleHAiOiIxOTAwNjY2MjI4IiwicHJvamVjdF9pZCI6IjUzYzdjMDZjZDEwODAwZGZmNjJjNTMzOGYxMWM0NDgyIiwidmVyIjoiMS4wLjAiLCJhdWQiOiJkZWxpdmVyLmtlbnRpY29jbG91ZC5jb20ifQ.PQz-3amLWjgOoGqorTdUc9gFBCutqIObqbQZiJqP71w
  front_matter_resolver: FrontMatterResolver
  content_resolver: ContentResolver
  filename_resolver: FilenameResolver
  data_resolver: DataResolver
  content_link_resolver: ContentLinkResolver
  inline_content_item_resolver: InlineContentItemResolver
  max_linked_items_depth: 5
  default_layout: default
  languages:
    - en-US
    - fr-FR
  posts:
    type: blog_post
    date: published
    layout: post
    tags: post_tags
    categories: post_categories
  pages:
    home:
    page:
    author:
      title: name
      layout: author
      collection: authors
  taxonomies:
    - navigation
