future: true
name: Radek
auto: false
baseurl: /jekyll-blog
sass:
  style: compact # possible values: nested expanded compact compressed
plugins:
- jekyll-kentico
kentico:
  project_id: ENV_PROJECT_ID
  secure_key: ENV_DELIVERY_API_KEY
  default_layout: default
  content_link_resolver: ContentLinkResolver
  inline_content_item_resolver: InlineContentItemResolver
  max_linked_items_depth: 5
  posts:
    content_type: blog_post
    layout: post
  pages:
    index: taxonomied_home_page
    layout: default
    content_type:
      taxonomied_page:
        layout: page
        layouts:
          taxonomied_home_page: home
          taxonomied_authors_page: authors
          taxonomied_categories_page: categories
      author:
        layout: author
        collection: authors
      category:
        layout: category
        collection: categories
  taxonomies:
    - site
