future: true
name: Radek
auto: false
baseurl: /jekyll_test
sass:
  style: compact # possible values: nested expanded compact compressed
permalink: pretty
collections:
  pages:
    output: true
    permalink: /:path/
    content_type: taxonomied_page
    layout: default
    layouts:
      taxonomied_home_page: home
      taxonomied_authors_page: authors
      taxonomied_categories_page: categories
  posts:
    output: true
    content_type: blog_post
    layout: post
    page_name: PostFilenameMapper
    linked_items:
      authors: AuthorsMapper
      categories: CategoriesMapper
  authors:
    output: true
    content_type: author
    layout: author
  categories:
    output: true
    content_type: category
    layout: category
kentico:
  project_id: ENV_PROJECT_ID
  secure_key: ENV_DELIVERY_API_KEY
  default_layout: default
  index_page: taxonomied_home_page
  taxonomies:
    - site